// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Models.Data;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Models.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Proxies:ChangeTracking", false)
                .HasAnnotation("Proxies:CheckEquality", false)
                .HasAnnotation("Proxies:LazyLoading", true)
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Models.Models.Appointment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("AppointmentDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("HairStyleId")
                        .HasColumnType("integer");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("HairStyleId");

                    b.HasIndex("UserId");

                    b.ToTable("Appointments");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AppointmentDate = new DateTime(2025, 3, 10, 10, 0, 0, 0, DateTimeKind.Utc),
                            HairStyleId = 1,
                            Status = 1,
                            UserId = 1
                        },
                        new
                        {
                            Id = 2,
                            AppointmentDate = new DateTime(2025, 3, 11, 14, 0, 0, 0, DateTimeKind.Utc),
                            HairStyleId = 3,
                            Status = 0,
                            UserId = 2
                        },
                        new
                        {
                            Id = 3,
                            AppointmentDate = new DateTime(2025, 3, 12, 9, 0, 0, 0, DateTimeKind.Utc),
                            HairStyleId = 4,
                            Status = 0,
                            UserId = 3
                        });
                });

            modelBuilder.Entity("Models.Models.HairStyle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<int?>("DurationMaxMinutes")
                        .HasColumnType("integer");

                    b.Property<int>("DurationMinutes")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PhotoUrl")
                        .HasColumnType("text");

                    b.Property<decimal?>("PriceMax")
                        .HasColumnType("numeric");

                    b.Property<decimal>("PriceMin")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.ToTable("HairStyles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DurationMaxMinutes = 120,
                            DurationMinutes = 60,
                            Name = "Tinte permanente",
                            PriceMax = 90m,
                            PriceMin = 35m
                        },
                        new
                        {
                            Id = 2,
                            DurationMaxMinutes = 120,
                            DurationMinutes = 60,
                            Name = "Tinte demipermanente",
                            PriceMax = 50m,
                            PriceMin = 35m
                        },
                        new
                        {
                            Id = 3,
                            DurationMaxMinutes = 360,
                            DurationMinutes = 240,
                            Name = "Baño de color",
                            PriceMin = 35m
                        },
                        new
                        {
                            Id = 4,
                            DurationMaxMinutes = 360,
                            DurationMinutes = 240,
                            Name = "Técnicas de mechas y efectos de luz",
                            PriceMax = 230m,
                            PriceMin = 140m
                        },
                        new
                        {
                            Id = 5,
                            DurationMaxMinutes = 360,
                            DurationMinutes = 240,
                            Name = "Balayage",
                            PriceMax = 250m,
                            PriceMin = 150m
                        },
                        new
                        {
                            Id = 6,
                            DurationMaxMinutes = 360,
                            DurationMinutes = 240,
                            Name = "Baby Lights",
                            PriceMax = 250m,
                            PriceMin = 150m
                        },
                        new
                        {
                            Id = 7,
                            DurationMaxMinutes = 360,
                            DurationMinutes = 240,
                            Name = "Ombré",
                            PriceMax = 230m,
                            PriceMin = 150m
                        },
                        new
                        {
                            Id = 8,
                            DurationMaxMinutes = 360,
                            DurationMinutes = 240,
                            Name = "Californianas",
                            PriceMax = 200m,
                            PriceMin = 100m
                        },
                        new
                        {
                            Id = 9,
                            DurationMinutes = 60,
                            Name = "Cortes dama",
                            PriceMin = 20m
                        },
                        new
                        {
                            Id = 10,
                            DurationMinutes = 180,
                            Name = "Permanente hombres",
                            PriceMin = 100m
                        },
                        new
                        {
                            Id = 11,
                            DurationMaxMinutes = 420,
                            DurationMinutes = 300,
                            Name = "Keratina",
                            PriceMax = 250m,
                            PriceMin = 140m
                        },
                        new
                        {
                            Id = 12,
                            DurationMaxMinutes = 420,
                            DurationMinutes = 240,
                            Name = "Aminoácido",
                            PriceMax = 300m,
                            PriceMin = 150m
                        },
                        new
                        {
                            Id = 13,
                            DurationMaxMinutes = 240,
                            DurationMinutes = 180,
                            Name = "Terapia capilar",
                            PriceMax = 200m,
                            PriceMin = 120m
                        },
                        new
                        {
                            Id = 14,
                            DurationMaxMinutes = 120,
                            DurationMinutes = 60,
                            Name = "Cepillados",
                            PriceMax = 50m,
                            PriceMin = 30m
                        },
                        new
                        {
                            Id = 15,
                            DurationMaxMinutes = 180,
                            DurationMinutes = 60,
                            Name = "Peinados",
                            PriceMax = 70m,
                            PriceMin = 35m
                        });
                });

            modelBuilder.Entity("Models.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<string>("SupabaseUserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("SupabaseUserId")
                        .IsUnique();

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            FirstName = "Jean",
                            LastName = "Tremblay",
                            PhoneNumber = "514-123-4567",
                            SupabaseUserId = "11111111-1111-1111-1111-111111111111"
                        },
                        new
                        {
                            Id = 2,
                            FirstName = "Marie",
                            LastName = "Dupont",
                            PhoneNumber = "438-987-6543",
                            SupabaseUserId = "22222222-2222-2222-2222-222222222222"
                        },
                        new
                        {
                            Id = 3,
                            FirstName = "Luc",
                            LastName = "Bernard",
                            PhoneNumber = "450-555-1234",
                            SupabaseUserId = "33333333-3333-3333-3333-333333333333"
                        });
                });

            modelBuilder.Entity("Models.Models.Appointment", b =>
                {
                    b.HasOne("Models.Models.HairStyle", "HairStyle")
                        .WithMany("Appointments")
                        .HasForeignKey("HairStyleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Models.Models.User", "User")
                        .WithMany("Appointments")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("HairStyle");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Models.Models.HairStyle", b =>
                {
                    b.Navigation("Appointments");
                });

            modelBuilder.Entity("Models.Models.User", b =>
                {
                    b.Navigation("Appointments");
                });
#pragma warning restore 612, 618
        }
    }
}
